
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Amani Newton
 */
public class Trans extends javax.swing.JFrame {

    int a;

    /**
     * Creates new form Trans
     */
    public Trans() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PASS = new javax.swing.JLabel();
        AMNT = new javax.swing.JLabel();
        WID = new javax.swing.JButton();
        DEP = new javax.swing.JButton();
        TRANS = new javax.swing.JButton();
        amnt = new javax.swing.JTextField();
        STATE = new javax.swing.JButton();
        ACNO = new javax.swing.JLabel();
        acno = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lout = new javax.swing.JButton();
        rpass = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        PASS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        PASS.setText("Password");

        AMNT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AMNT.setText("Amount");

        WID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        WID.setText("Withdraw");
        WID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WIDActionPerformed(evt);
            }
        });

        DEP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DEP.setText("Deposit");
        DEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DEPActionPerformed(evt);
            }
        });

        TRANS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TRANS.setText("Transfer");
        TRANS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TRANSActionPerformed(evt);
            }
        });

        amnt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        STATE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        STATE.setText("Account Status");
        STATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STATEActionPerformed(evt);
            }
        });

        ACNO.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ACNO.setText("Account Number");

        acno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        acno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acnoActionPerformed(evt);
            }
        });

        pass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        jLabel1.setText("Transactions");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        lout.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lout.setText("Log Out");
        lout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loutActionPerformed(evt);
            }
        });

        rpass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rpass.setText("Change Password");
        rpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lout, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ACNO, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WID, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AMNT, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(DEP, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                            .addComponent(rpass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(PASS, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(70, 70, 70))))))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(STATE, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(amnt)
                            .addComponent(acno)
                            .addComponent(pass)
                            .addComponent(TRANS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ACNO))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PASS)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AMNT)
                    .addComponent(amnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(STATE)
                    .addComponent(WID))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TRANS)
                    .addComponent(DEP))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lout)
                    .addComponent(rpass))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void WIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WIDActionPerformed

        int selectedOption = JOptionPane.showConfirmDialog(null,
                "Do you wish to proceed with withdrawal",
                "CONFRIM ACTION!",
                JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {
            String ac = acno.getText();
            String p = pass.getText();
            String aa = amnt.getText();

            try {
                Class.forName("com.mysql.jdbc.Driver");

                String path = "jdbc:mysql://localhost:3306/transbank";
                String user = "root";
                String passw = "";

                Connection con = DriverManager.getConnection(path, user, passw);
                Statement stmt = con.createStatement();
                Statement stmt1 = con.createStatement();
                Statement stmt2 = con.createStatement();
                ResultSet rs;

                if (ac.isEmpty() || p.isEmpty() || aa.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Empty Field(s)\nPlease input correct details!", "NULL INPUT", JOptionPane.PLAIN_MESSAGE);
                } else {
                    String sql = "select amount from balance where AccountNo=('" + ac + "')";
                    rs = stmt.executeQuery(sql);

                    int wida = Integer.parseInt(aa);
                    while (rs.next()) {
                        a = rs.getInt("Amount");
                    }
                    if (wida > a) {
                        JOptionPane.showMessageDialog(null, "Insuficient funds!", "CUSTOMER ACCOUNT", JOptionPane.PLAIN_MESSAGE);
                    } else {

                        int t = a - wida;

                        String query = "update balance set amount =('" + t + "') where AccountNo =('" + ac + "')";
                        stmt1.execute(query);
                        String f = Integer.toString(t);
                        amnt.setText(f);
                        String query1 = "INSERT INTO withdraw(AccountNo,Amount) VALUES ('" + ac + "','" + aa + "') ";
                        stmt2.execute(query1);

                        JOptionPane.showMessageDialog(null, "Withdrawn Ksh " + aa + " Successfully!\nNew Balance is: " + t + "",
                                "CUSTOMER ACCOUNT", JOptionPane.PLAIN_MESSAGE);
                    }
                    Trans tr = new Trans();
                    tr.setVisible(true);
                    dispose();
                }
            } catch (HeadlessException | ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error!\n" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);
                amnt.setText(null);
                acno.setText(null);
                pass.setText(null);
            }
        }
    }//GEN-LAST:event_WIDActionPerformed

    private void DEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DEPActionPerformed

        int selectedOption = JOptionPane.showConfirmDialog(null,
                "Do you wish to proceed with deposit",
                "CONFRIM ACTION!",
                JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {
            String ac = acno.getText();
            String p = pass.getText();
            String aa = amnt.getText();

            try {
                Class.forName("com.mysql.jdbc.Driver");

                String path = "jdbc:mysql://localhost:3306/transbank";
                String user = "root";
                String passw = "";
                int t;
                Connection con = DriverManager.getConnection(path, user, passw);
                Statement stmt = con.createStatement();
                Statement stmt1 = con.createStatement();
                Statement stmt2 = con.createStatement();
                Statement stmt3 = con.createStatement();
                ResultSet rs;
                ResultSet rsl;

                String sql = "select amount from balance where AccountNo=('" + ac + "')";
                rs = stmt.executeQuery(sql);
                String get = "select AccountNo, Password from login where AccountNo=('" + ac + "')";
                rsl = stmt3.executeQuery(get);

                if (ac.isEmpty() || p.isEmpty() || aa.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Empty Field(s)\nPlease input correct details!",
                            "NULL INPUT", JOptionPane.PLAIN_MESSAGE);
                } else {

                    while (rs.next()) {
                        int x = rs.getInt("amount");
                        int mn1 = Integer.parseInt(aa);
                        t = mn1 + x;
                        String query = "update balance set amount =('" + t + "') where AccountNo =('" + ac + "')";
                        stmt1.execute(query);

                        String query1 = "INSERT INTO deposit(AccountNo,Amount) VALUES ('" + ac + "','" + aa + "') ";
                        stmt2.execute(query1);

                        JOptionPane.showMessageDialog(null, "Deposited Ksh " + aa + " succesfully\nNew balance is: " + t + "",
                                "DEPOSIT", JOptionPane.PLAIN_MESSAGE
                        );

                        Trans tr = new Trans();
                        tr.setVisible(true);
                        dispose();
                    }
                }
            } catch (HeadlessException | ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error!\n" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);
                amnt.setText(null);
                acno.setText(null);
                pass.setText(null);
            }
        }
    }//GEN-LAST:event_DEPActionPerformed

    private void acnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acnoActionPerformed

    private void STATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STATEActionPerformed

        String accno = JOptionPane.showInputDialog(null, "Please input Account Number");
        if (accno.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Empty field!\nPlease input correct details!", 
                    "USER ALERT!", JOptionPane.PLAIN_MESSAGE);
        } else {
            try {
                Class.forName("com.mysql.jdbc.Driver");

                String path = "jdbc:mysql://localhost:3306/transbank";
                String user = "root";
                String passw = "";

                Connection con = DriverManager.getConnection(path, user, passw);
                Statement stmt = con.createStatement();
                Statement stmt1 = con.createStatement();
                ResultSet rs;
                ResultSet rs1;

                String sql = "select Amount from balance where AccountNo=('" + accno + "')";
                rs = stmt.executeQuery(sql);
                String query = "select Fname, Lname, Email from newacc where AccountNo=('" + accno + "')";
                rs1 = stmt1.executeQuery(query);
                while (rs.next()) {
                    int Balance = rs.getInt("Amount");
                    String sum = Integer.toString(Balance);
                    while (rs1.next()) {
                        String nme = rs1.getString("Fname");
                        String nmes = rs1.getString("Lname");
                        String meil = rs1.getString("Email");
                        JOptionPane.showMessageDialog(null, "Account Owner: " + nme + " " + nmes + "\nYour balance is: " + sum + ""
                                + "\n Valid user mail(s): " + meil + " \n"
                                        + "\n---Trans Bank Online Services---",
                                "OWNER INFO", JOptionPane.PLAIN_MESSAGE);
                    }
                }

            } catch (HeadlessException | ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error!\n" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            Trans tr = new Trans();
            tr.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_STATEActionPerformed

    private void TRANSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TRANSActionPerformed
        String nacc = JOptionPane.showInputDialog(null, "Please input recepient's Account Number");
        int selectedOption = JOptionPane.showConfirmDialog(null,
                "Proceed to cash transfer",
                "CONFRIM ACTION!",
                JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {

            String ac = acno.getText();
            String p = pass.getText();
            String bb = amnt.getText();
            if (ac.isEmpty() || p.isEmpty() || bb.isEmpty() || nacc.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Empty Field(s)!\nPlease try again", "NULL INPUT", JOptionPane.PLAIN_MESSAGE);
            } else {
                try {
                    Class.forName("com.mysql.jdbc.Driver");

                    String path = "jdbc:mysql://localhost:3306/transbank";
                    String user = "root";
                    String passw = "";
                    Connection con = DriverManager.getConnection(path, user, passw);
                    Statement stmt = con.createStatement();
                    Statement stmt1 = con.createStatement();
                    Statement stmt2 = con.createStatement();
                    Statement stmt3 = con.createStatement();
                    ResultSet rs;
                    ResultSet rs1;

                    String sql = "select Amount from balance where AccountNo=('" + nacc + "')";
                    rs = stmt.executeQuery(sql);

                    while (rs.next()) {
                        int q = rs.getInt("Amount");
                        int namt = Integer.parseInt(bb);
                        int w = namt + q;

                        String sqls = "update balance set Amount = ('" + w + "') where AccountNo = ('" + nacc + "')";
                        stmt1.execute(sqls);
                        String e = Integer.toString(w);
                        amnt.setText(e);
                    }

                    String que = "select Amount from balance where AccountNo=('" + ac + "')";
                    rs1 = stmt.executeQuery(que);
                    while (rs1.next()) {
                        int s = rs1.getInt("Amount");
                        int namts = Integer.parseInt(bb);
                        int d = s - namts;

                        String query = "update balance set Amount = ('" + d + "') where AccountNo = ('" + ac + "')";
                        stmt3.execute(query);
                        String g = Integer.toString(d);
                        amnt.setText(g);
                    }
                    String sqlss = "insert into transfer(SenderAccNo, Amount, RecepientAccNo) values ('" + ac + "','" + bb + "','" + nacc + "')";
                    stmt2.execute(sqlss);
                    JOptionPane.showMessageDialog(null, "Transaction Successful!\nYou have transfered Ksh " + bb + " to account number " + nacc + "",
                            "TRANSFER", JOptionPane.PLAIN_MESSAGE);

                    Trans tr = new Trans();
                    tr.setVisible(true);
                    dispose();
                } catch (HeadlessException | ClassNotFoundException | SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Error!\n" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);
                    amnt.setText(null);
                    acno.setText(null);
                    pass.setText(null);
                }
            }
        }
    }//GEN-LAST:event_TRANSActionPerformed

    private void loutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loutActionPerformed
        int selectedOption = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to log out",
                "CONFRIM ACTION!",
                JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Thank you for choosing Transit Bank",
                    "LOGGING OUT!", JOptionPane.PLAIN_MESSAGE);
            Home h = new Home();
            h.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_loutActionPerformed

    private void rpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpassActionPerformed

        String p1 = JOptionPane.showInputDialog(null, "Please input Account Number");
        String p3 = JOptionPane.showInputDialog(null, "Input new password");
        int selectedOption = JOptionPane.showConfirmDialog(null,
                "Do you wish to proceed?",
                "CONFRIM ACTION!",
                JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {

            try {
                Class.forName("com.mysql.jdbc.Driver");

                String path = "jdbc:mysql://localhost:3306/transbank";
                String user = "root";
                String passw = "";

                Connection con = DriverManager.getConnection(path, user, passw);
                Statement stmt = con.createStatement();

                String query = "update newacc set Password ='" + p3 + "' where AccountNo='" + p1 + "'";
                stmt.execute(query);
                String query1 = "update login set Password ='" + p3 + "' where AccountNo='" + p1 + "'";
                stmt.execute(query1);

                if (p1.isEmpty() || p3.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Empty Field(s)!Please Input Detail(s)!",
                            "INPUT DETAILS", JOptionPane.PLAIN_MESSAGE);

                } else {
                    JOptionPane.showMessageDialog(null, "You have successfully changed your password!", "PASSWORD CHANGE", JOptionPane.PLAIN_MESSAGE);
                    Login lg = new Login();
                    lg.setVisible(true);
                    dispose();
                }
            } catch (HeadlessException | ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error!\n" + ex, "ERROR", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_rpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trans().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ACNO;
    private javax.swing.JLabel AMNT;
    private javax.swing.JButton DEP;
    private javax.swing.JLabel PASS;
    private javax.swing.JButton STATE;
    private javax.swing.JButton TRANS;
    private javax.swing.JButton WID;
    private javax.swing.JTextField acno;
    private javax.swing.JTextField amnt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton lout;
    private javax.swing.JPasswordField pass;
    private javax.swing.JButton rpass;
    // End of variables declaration//GEN-END:variables
}
